export default {
  SET_SEARCH: 'SET_SEARCH',

  FETCH_CEP_SUCCESS: 'FETCH_CEP_SUCCESS',
  FETCH_CEP_FAILURE: 'FETCH_CEP_FAILURE',
  FETCH_CEP_REQUEST: 'FETCH_CEP_REQUEST',

  TOGGLE_CEP: 'TOGGLE_CEP',
};
